name: PR

on: pull_request

jobs:
  format_lint_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Install
        run: pnpm i
      - name: Prettier
        run: npx prettier --check .
      - name: ESLint
        run: npx eslint . --max-warnings=0
